<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{2de65154-975d-4f1a-b566-e7882660a616}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
bAlwaysTrue  	AT%Q* 	: BOOL := TRUE;
bRun 		 	AT%Q* 	: BOOL;
bErrAck 		AT%Q*	: BOOL;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>